/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./Arjuna.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import file from "./Arjuna.glb"

export default function Arjuna(props) {
  const { nodes, materials } = useGLTF(file)
  return (
    <group {...props} dispose={null} scale={.17}> 
      <mesh geometry={nodes.Arjuna.geometry} material={materials['default']} rotation={[Math.PI / 2, 0, Math.PI / 6]} scale={0.28} />
    </group>
  )
}

useGLTF.preload(file)
