/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./Bael.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import file from "./Bael.glb"

export default function Bael(props) {
  const { nodes, materials } = useGLTF(file)
  return (
    <group {...props} dispose={null} scale={.5}>
      <mesh geometry={nodes.Bael.geometry} material={materials['Material.007']} rotation={[Math.PI / 2, 1.07, 0]} scale={0.2} />
    </group>
  )
}

useGLTF.preload(file)
