/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./Banyan.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import file from './Banyan.glb'

export default function Banyan(props) {
  const { nodes, materials } = useGLTF(file)
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes['2'].geometry} material={materials['Material.003']} rotation={[0, Math.PI /2 , Math.PI / 2]} scale={0.07} />
    </group>
  )
}

useGLTF.preload('/Banyan.glb')
