/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./Neem.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import file from "./Neem.glb"

export default function Neem(props) {
  const { nodes, materials } = useGLTF(file)
  return (
    <group {...props} dispose={null} rotation={[Math.PI / 1, 0, 0]} scale={5}>
      <mesh geometry={nodes['1'].geometry} material={materials['Material.001']} rotation={[Math.PI / 2, 0, 0]} scale={-0.02} />
    </group>
  )
}

useGLTF.preload(file)
