/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./Banyan.glb
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import file from './Peepal.glb'

export default function Peepal(props) {
  const { nodes, materials } = useGLTF(file)
  return (
    <group {...props} dispose={null} scale={.4}>
      <mesh geometry={nodes['ImageToStlcom_peepal-leaf-png-transparent-image'].geometry} material={materials['Material.005']} rotation={[Math.PI / 2, 0, 0]} scale={0.18} />
    </group>
  )
}

useGLTF.preload(file)
