/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./abhi.glb
*/

import React, { useRef } from 'react'
import { useGLTF,MeshDistortMaterial, Sphere } from '@react-three/drei'
import file from "./abhi.glb"
import texture from "../../images/tex2.avif"
import {  useLoader } from '@react-three/fiber'
import { TextureLoader } from 'three'

export default function Model(props) {
  const colorMap = useLoader(TextureLoader, texture)
  const { nodes, materials } = useGLTF(file)
  return (
    <Sphere>

    </Sphere>
  )
}

useGLTF.preload(file)
