/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./LL.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import file from "./LL.glb"

export default function Model(props) {
  const { nodes, materials } = useGLTF(file)
  return (
    <group {...props} dispose={null} scale={.6}>
      <mesh geometry={nodes.Suzanne.geometry} material={nodes.Suzanne.material} position={[0.07, 3.36, -0.09]} rotation={[-0.18, -0.02, -0.06]} scale={0.86} />
      <mesh geometry={nodes.Text.geometry} material={nodes.Text.material} position={[-2.25, 1.47, -0.49]} rotation={[Math.PI / 2, 0, 0]} scale={0.95} />
    </group>
  )
}

useGLTF.preload(file)
